# fly.toml app configuration file generated for lofi-env on 2024-09-14T23:27:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lofi-env'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
