name: Lofi-env CI/CD Pipeline

on:
  push:
    paths-ignore:
      - "README.md"
      - "images/"
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - name: Run unit & integration tests
        run: ./ops/scripts/run-tests.sh

  build:
    name: 🐳 Build & publish docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker image
        run: ./ops/scripts/build-publish.sh
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: 🚀 Deploy to production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: ./ops/scripts/deploy.sh
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_URI: ${{ secrets.DB_URI }}
          PORT: 4000
          ENV: "prod"
